name: jekyll

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
    - uses: docker://jekyll/builder:latest 
      run: jekyll
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
