name: jekyll

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker://jekyll/builder:latest
    - name: Run a one-line script      
    - run: |
     pwd
     ls 
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
